### ISSUE TITLE
AxTrade Trade GUI Menu

### ISSUE THREAD

**Issue by Mr-Fires** [JavaPlugins/addons-listing#1]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Spectra Studios
title: AxTrade Trade GUI Menu
content: A trade menu like never seen before.
premium: True
icon: imgurlUrlHere
banner: https://imgur.com/u6ePJ9r
links:
  - https://builtbybit.com/resources/axtrade-trade-gui-menu.59004/
```
