### ISSUE TITLE
Spirit Mob Balloons

### ISSUE THREAD

**Issue by Mr-Fires** [JavaPlugins/addons-listing#2]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Spectra Studios
title: Spirit Mob Balloons
content: Add vibrant Spirit Mob balloons to your Minecraft builds for a festive, spooky touch!
premium: True
icon: imgurlUrlHere
banner: https://imgur.com/cNAwjUE
links:
  - https://bbyb.it/r/53914/
```
