### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by Endgamer196** [JavaPlugins/addons-listing#4]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: author
title: YourTitleHere
content: YourDescriptionHere
premium: false
icon: imgurlUrlHere
banner: imgurlUrlHere
links:
  - https://spigotmc.org/resources/xxxxxx
  - https://builtbybit.com/resources/xxxxxx
```
