### ISSUE TITLE
Ultra Dances

### ISSUE THREAD

**Issue by mario638** [JavaPlugins/addons-listing#6]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: mario638
title: Ultra Dances
content: an ItemsAdder addon for adding more emotes
premium: true
icon: https://images.polymart.org/resource/2899/thumbnail.png
banner: https://images.polymart.org/resource/2899/header.png
links:
  - https://polymart.org/resource/ultra-dances.2899
```
