### ISSUE TITLE
Vanilla MC UIs

### ISSUE THREAD

**Issue by Andre601** [JavaPlugins/addons-listing#7]
### Terms

- [x] My resource is not using any assets that I have no ownership of
- [x] My resource doesn't contain the ItemsAdder JAR or any default ItemsAdder asset

### Resource information file (YML)

```yml
author: Andre601
title: Vanilla MC UIs
content: A tedious recreation of Vanilla GUIs as font images to use in chest UIs.
premium: false
icon: https://www.spigotmc.org/data/resource_icons/97/97859.jpg
banner: https://www.spigotmc.org/data/resource_icons/97/97859.jpg # Don't have a banner
links:
  - https://www.spigotmc.org/resources/97859/
```
